# Generated by Django 6.0.6 on 2026-09-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_project_projecttask_tasksubtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoaura',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
