# Generated by Django 6.0.6 on 2026-09-17 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_elementoaura_fecha_inicio_goal_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('meeting_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='General', max_length=50)),
                ('color_hex', models.CharField(default='#3B82F6', max_length=7)),
                ('status', models.CharField(choices=[('PROGRAMMED', 'Programado'), ('COMPLETED', 'Completado'), ('CANCELED', 'Cancelado')], default='PROGRAMMED', max_length=20)),
                ('reminder_minutes', models.PositiveIntegerField(blank=True, default=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aura_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
