# Generated by Django 6.0.6 on 2026-09-24 17:21

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='progress_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='goalmilestone',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='eventitem',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gte', models.F('start_time'))), name='event_end_time_gte_start_time'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percentage__gte', 0), ('progress_percentage__lte', 100)), name='goal_progress_percentage_0_100'),
        ),
        migrations.AddConstraint(
            model_name='goalmilestone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('weight__gte', 1), ('weight__lte', 100)), ('weight__isnull', True), _connector='OR'), name='goal_milestone_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percentage__gte', 0), ('progress_percentage__lte', 100)), name='project_progress_percentage_0_100'),
        ),
    ]
