# Generated by Django 6.0.6 on 2026-09-24 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_goal_progress_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventitem',
            index=models.Index(fields=['user', 'start_time', 'end_time'], name='event_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='eventitem',
            index=models.Index(fields=['user', 'status'], name='event_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goal_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', '-created_at'], name='goal_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notif_user_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'status'], name='project_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-created_at'], name='project_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'status'], name='proj_task_status_idx'),
        ),
    ]
