# Generated by Django 6.0.6 on 2026-09-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_goal_reminder_minutes_projecttask_reminder_minutes'),
        ('backend', '0009_eventitem_deleted_at_eventitem_is_deleted_and_more'),
    ]

    operations = [
    ]
