# Generated by Django 6.0.6 on 2026-09-29 14:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_merge_20260928_0451'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('COURSE', 'Curso'), ('BOOK', 'Libro'), ('ARTICLE', 'Artículo'), ('TECH_DOC', 'Documentación Técnica')], default='COURSE', max_length=20)),
                ('platform_name', models.CharField(blank=True, max_length=100, null=True)),
                ('platform_url', models.URLField(blank=True, max_length=500, null=True)),
                ('color_hex', models.CharField(default='#8B5CF6', max_length=7)),
                ('status', models.CharField(choices=[('BACKLOG', 'Por empezar'), ('IN_PROGRESS', 'En curso'), ('PAUSED', 'En pausa'), ('COMPLETED', 'Completado')], default='BACKLOG', max_length=20)),
                ('progress_mode', models.CharField(choices=[('MANUAL', 'Manual'), ('TOPICS', 'Por Temas / Módulos')], default='TOPICS', max_length=20)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_unit', models.PositiveIntegerField(default=0)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('last_point_reached', models.CharField(blank=True, max_length=250, null=True)),
                ('takeaways_markdown', models.TextField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dormancy_alert_days', models.PositiveSmallIntegerField(default=7)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_items', to='backend.goal')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_items', to='backend.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aura_learning_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section_name', models.CharField(blank=True, max_length=150, null=True)),
                ('learning_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='backend.learningitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='learningitem',
            index=models.Index(fields=['user', 'status'], name='learning_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='learningitem',
            index=models.Index(fields=['user', 'resource_type'], name='learning_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='learningitem',
            index=models.Index(fields=['user', '-last_activity_at'], name='learning_user_act_idx'),
        ),
    ]
