# Generated by Django 6.0.6 for Aura Phases 1 to 4

import uuid
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0011_learningitem_learningtopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='time_horizon',
            field=models.CharField(
                choices=[('SHORT_TERM', 'Corto Plazo'), ('LONG_TERM', 'Largo Plazo')],
                default='SHORT_TERM',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='goal',
            name='parent_goal',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sub_goals',
                to='backend.goal',
            ),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress_mode',
            field=models.CharField(
                choices=[
                    ('MANUAL', 'Manual'),
                    ('MILESTONES', 'Hitos / Automático'),
                    ('CONNECTED', 'Conectado / Multifactorial'),
                ],
                default='MILESTONES',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='ActivityCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('is_completed', models.BooleanField(default=True)),
                ('streak_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_item', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='check_ins',
                    to='backend.eventitem',
                )),
                ('learning_item', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='check_ins',
                    to='backend.learningitem',
                )),
                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='activity_checkins',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='activitycheckin',
            constraint=models.UniqueConstraint(
                condition=models.Q(learning_item__isnull=False),
                fields=('user', 'learning_item', 'date'),
                name='unique_user_learning_checkin_per_day',
            ),
        ),
        migrations.AddConstraint(
            model_name='activitycheckin',
            constraint=models.UniqueConstraint(
                condition=models.Q(event_item__isnull=False),
                fields=('user', 'event_item', 'date'),
                name='unique_user_event_checkin_per_day',
            ),
        ),
        migrations.AddIndex(
            model_name='activitycheckin',
            index=models.Index(fields=['user', 'date'], name='checkin_user_date_idx'),
        ),
    ]
