# Generated by Django 6.0.6 on 2026-10-06 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_projecttask_kanban_5_columns_and_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningitem',
            name='dropped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='dropped_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='is_focus',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='learningitem',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Por empezar'), ('IN_PROGRESS', 'En curso'), ('PAUSED', 'En pausa'), ('COMPLETED', 'Completado'), ('DROPPED', 'Descartado')], default='BACKLOG', max_length=20),
        ),
        migrations.AddIndex(
            model_name='learningitem',
            index=models.Index(fields=['user', 'is_focus'], name='learning_user_focus_idx'),
        ),
    ]
