# Generated by Django 6.0.6 on 2026-07-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoAura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('OBJETIVO', 'Objetivo'), ('PROYECTO', 'Proyecto'), ('EVENTO', 'Evento'), ('ACTIVIDAD', 'Actividad')], max_length=20)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('color_hex', models.CharField(default='#6366F1', max_length=7)),
            ],
        ),
    ]
